### Publik endppoint
GET http://localhost:5190/public

### Logga in som användare
POST http://localhost:5190/login
Content-Type: application/json

{
  "username": "user",
  "password": "Password123!"
}

### Logga in admin
POST http://localhost:5190/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password123!"
}

### Bara för inloggade användare (använd token från login response)
GET http://localhost:5190/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTlhMWRkNmYtZmUyNS00NGJjLTkyNDEtZjBjZjk0ZTk4MGI5IiwiZXhwIjoxNzczMzExNjM5LCJpc3MiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgiLCJhdWQiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgifQ.XzUeVeNwJYygTbQ9GElN-CuKcxYsI-5zUuniocy13wQ

### Admin only!
GET http://localhost:5190/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjYyY2QzZWY4LTFlYTAtNDE5OC1iY2MxLTRlYzM4NzMwYjliMCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzczMzExODc1LCJpc3MiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgiLCJhdWQiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgifQ.d3G-lZPom088aaCnmwBorOso4aHcFRxnQvjySC8P1eo

###

POST http://localhost:5190/api/things
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTlhMWRkNmYtZmUyNS00NGJjLTkyNDEtZjBjZjk0ZTk4MGI5IiwiZXhwIjoxNzczMjcyNTMzLCJpc3MiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgiLCJhdWQiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgifQ.d_py7uM6C8YGeVwERbTXqApfkb-U72fPbrdyxRB0mqY

{
  "name": "My First Thing",
  "description": "This is a description of my first thing."
}

### Hämta alla saker
GET http://localhost:5190/api/things
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMTlhMWRkNmYtZmUyNS00NGJjLTkyNDEtZjBjZjk0ZTk4MGI5IiwiZXhwIjoxNzczMjcyNTMzLCJpc3MiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgiLCJhdWQiOiJXZWJBcGlJZGVudGl0eUpXVEF1dGgifQ.d_py7uM6C8YGeVwERbTXqApfkb-U72fPbrdyxRB0mqY

